In [1]:
import numpy as np 
import pandas as pd 
import matplotlib.pyplot as plt 
import seaborn as sns 
from sklearn.preprocessing import LabelEncoder , StandardScaler
from sklearn.model_selection import train_test_split , cross_val_score , RandomizedSearchCV
from sklearn.tree import DecisionTreeRegressor 
from sklearn.svm import SVR 
from sklearn.linear_model import LinearRegression
from sklearn.neighbors import KNeighborsRegressor
from sklearn.naive_bayes import GaussianNB
from sklearn.ensemble import RandomForestRegressor
from xgboost import XGBRegressor
from sklearn.metrics import mean_absolute_error , mean_squared_error , r2_score

In [2]:
df = pd.read_csv('../Artifacts/raw.csv')

In [3]:
import os

path = '../Artifacts/synthetic_customer_churn_100k.csv'

print("Exists:", os.path.exists(path))

if os.path.exists(path):
    print("Size:", os.path.getsize(path), "bytes")

Exists: True
Size: 0 bytes

In [4]:
import os

folder = '../Artifacts'

print(os.listdir(folder))

['clean_data.csv', 'raw.csv', 'synthetic_customer_churn_100k.csv', 'test.csv', 'train.csv']

In [5]:
import os

for file in ['clean_data.csv', 'raw.csv', 'synthetic_customer_churn_100k.csv', 'test.csv', 'train.csv']:
    path = '../Artifacts/' + file
    print(file, "=>", os.path.getsize(path) / (1024**2), "MB")

clean_data.csv => 1237.217926979065 MB
raw.csv => 5.996010780334473 MB
synthetic_customer_churn_100k.csv => 0.0 MB
test.csv => 1.1991968154907227 MB
train.csv => 4.796900749206543 MB

In [6]:
import pandas as pd

df = pd.read_csv('../Artifacts/raw.csv')

print(df.shape)
print(df.dtypes)
print(df.head())

(100000, 9)
customer_id          int64
age                  int64
gender              object
tenure               int64
monthly_charges    float64
contract            object
payment_method      object
total_charges      float64
churn               object
dtype: object
   customer_id  age  gender  tenure  monthly_charges        contract  \
0            1   56  Female      68           147.58        Two year
1            2   69    Male      32            22.54  Month-to-month
2            3   46  Female      10            52.47        One year
3            4   32    Male      22           109.67  Month-to-month
4            5   60  Female      54           130.98  Month-to-month

     payment_method  total_charges churn
0     Bank transfer       10052.03    No
1      Mailed check         686.78    No
2  Electronic check         537.88    No
3      Mailed check        2390.04   Yes
4       Credit card        7081.28    No

In [7]:
df = df.drop('customer_id', axis=1)

In [8]:
df.isnull().sum()

age                0
gender             0
tenure             0
monthly_charges    0
contract           0
payment_method     0
total_charges      0
churn              0
dtype: int64

In [9]:
df = pd.read_csv('../Artifacts/raw.csv')

In [10]:
df.head()

,customer_id,age,gender,tenure,monthly_charges,contract,payment_method,total_charges,churn
0,1,56,Female,68,147.58,Two year,Bank transfer,10052.03,No
1,2,69,Male,32,22.54,Month-to-month,Mailed check,686.78,No
2,3,46,Female,10,52.47,One year,Electronic check,537.88,No
3,4,32,Male,22,109.67,Month-to-month,Mailed check,2390.04,Yes
4,5,60,Female,54,130.98,Month-to-month,Credit card,7081.28,No

In [11]:
df.shape

(100000, 9)

In [12]:
df.drop_duplicates(inplace=True)

In [13]:
df.head()

,customer_id,age,gender,tenure,monthly_charges,contract,payment_method,total_charges,churn
0,1,56,Female,68,147.58,Two year,Bank transfer,10052.03,No
1,2,69,Male,32,22.54,Month-to-month,Mailed check,686.78,No
2,3,46,Female,10,52.47,One year,Electronic check,537.88,No
3,4,32,Male,22,109.67,Month-to-month,Mailed check,2390.04,Yes
4,5,60,Female,54,130.98,Month-to-month,Credit card,7081.28,No

In [14]:
df.shape

(100000, 9)

In [15]:
print("Before:", df.shape)

print("Exact duplicate rows:", df.duplicated().sum())

df = df.drop_duplicates()

print("After:", df.shape)

Before: (100000, 9)
Exact duplicate rows: 0
After: (100000, 9)

In [16]:
print("Duplicate customer_id:", df['customer_id'].duplicated().sum())

Duplicate customer_id: 0

In [17]:
df.head()

,customer_id,age,gender,tenure,monthly_charges,contract,payment_method,total_charges,churn
0,1,56,Female,68,147.58,Two year,Bank transfer,10052.03,No
1,2,69,Male,32,22.54,Month-to-month,Mailed check,686.78,No
2,3,46,Female,10,52.47,One year,Electronic check,537.88,No
3,4,32,Male,22,109.67,Month-to-month,Mailed check,2390.04,Yes
4,5,60,Female,54,130.98,Month-to-month,Credit card,7081.28,No

In [18]:
print(df['total_charges'].dtype)
print(df['customer_id'].dtype)
print(df['age'].dtype)
print(df['gender'].dtype)
print(df['tenure'].dtype)
print(df['monthly_charges'].dtype)
print(df['contract'].dtype)
print(df['payment_method'].dtype)
print(df['total_charges'].dtype)
print(df['churn'].dtype)

float64
int64
int64
object
int64
float64
object
object
float64
object

In [19]:
le=LabelEncoder()

In [20]:
cat_col=['gender' , 'contract' , 'payment_method' , 'churn']

In [21]:
for col in cat_col:
    df[col]=le.fit_transform(df[col])

In [22]:
df.head()

,customer_id,age,gender,tenure,monthly_charges,contract,payment_method,total_charges,churn
0,1,56,0,68,147.58,2,0,10052.03,0
1,2,69,1,32,22.54,0,3,686.78,0
2,3,46,0,10,52.47,1,2,537.88,0
3,4,32,1,22,109.67,0,3,2390.04,1
4,5,60,0,54,130.98,0,1,7081.28,0

In [23]:
print(df.dtypes)

customer_id          int64
age                  int64
gender               int64
tenure               int64
monthly_charges    float64
contract             int64
payment_method       int64
total_charges      float64
churn                int64
dtype: object

In [24]:
X=df.drop(['total_charges'] , axis=1)
y=df['total_charges']

In [25]:
X.head()

,customer_id,age,gender,tenure,monthly_charges,contract,payment_method,churn
0,1,56,0,68,147.58,2,0,0
1,2,69,1,32,22.54,0,3,0
2,3,46,0,10,52.47,1,2,0
3,4,32,1,22,109.67,0,3,1
4,5,60,0,54,130.98,0,1,0

In [26]:
y.head()

0    10052.03
1      686.78
2      537.88
3     2390.04
4     7081.28
Name: total_charges, dtype: float64

In [27]:
X_train , X_test , y_train , y_test=train_test_split(X , y , test_size=0.2 , random_state=42)

In [28]:
scaler=StandardScaler()
X_train_scal=scaler.fit_transform(X_train)
X_test_scal=scaler.fit_transform(X_test)

In [29]:
models={
    "LinearRegression":LinearRegression() , 
     "DecisionTreeRegressor":DecisionTreeRegressor() , 
    "XGBRegressor":XGBRegressor() ,
    "SVR":SVR() ,
    "KNeighborsRegressor":KNeighborsRegressor() , 
    "RandomForestRegressor":RandomForestRegressor()      


}

In [30]:
params={
    'LinearRegression':{
        'fit_intercept':[True , False], 
        "copy_X":[True, False],
        "n_jobs":[None , 1 , 2 , 3 , 5 , 9 , 25]
        
    } , 
  
    
    'XGBRegressor': {
    'objective': ['binary:logistic'],
    'max_depth': [3, 5, 6, 7, 10],
    'n_estimators': [50, 100, 200],
    'subsample': [0.8, 1.0],
    'colsample_bytree': [0.8, 1.0],
    'reg_alpha': [0, 0.1, 1],
    'reg_lambda': [1, 2],
    'gamma': [0, 0.1, 0.2],
    'booster': ['gbtree'],
    'tree_method': ['auto'],
    'scale_pos_weight': [1]
    },
    
    'SVR':{
        "kernel":['linear', 'poly', 'rbf', 'sigmoid'],
        "degree":[1 , 3 , 6 , 7 , 9 , 13, 25],
        "gamma":['scale', 'auto'],
        "epsilon":[0.1,0.3,0.5,0.6,0.8,0.9,1]
    
    } ,
      
    'KNeighborsRegressor':{
        "n_neighbors":[3 , 5 , 7 , 9 , 13 , 25],
        "weights":['uniform' , 'distance'],
        "algorithm":['auto', 'ball_tree', 'kd_tree', 'brute'],
        'leaf_size':[10, 20 , 30 , 35 , 40],
         
    } , 
      
        'DecisionTreeRegressor':{
            "criterion": ["squared_error", "absolute_error", "friedman_mse"],
            "max_depth": [None, 3, 5, 10, 20, 30],
            "min_samples_split":[2,3,4,5,6,7,8,9,10],
            "min_samples_leaf":[2,3,4,5,6,7,8,9,10],
            "max_features": [1 , "sqrt", "log2", None],
        } ,
    
    'RandomForestRegressor':{
        "criterion":['squared_error', 'absolute_error', 'poisson'],
        "max_depth":[None , 1 , 2 , 5 , 7 , 13 , 25],
        "min_samples_split":[2, 3 , 5],
        "min_samples_leaf":[1 , 2 , 3 , 5 , 7 , 9 , 25]
        
    } , 
    
    
    
}

In [31]:
best_model=None
best_model_name=None
best_model_score=0

In [32]:
# for name, model in models.items():
#     print('-' * 100)
#     print('Name:', name)

#     search = RandomizedSearchCV(
#         estimator=model,
#         cv=5,
#         param_distributions=params[name],
#         n_iter=20,
#         random_state=42,
#         scoring="r2"
#     )

#     search.fit(X_train_scal, y_train)

#     y_predict = search.predict(X_test_scal)

#     print("Best Score:", search.best_score_)
#     print("R2 Score:", r2_score(y_test, y_predict))
#     print("Best Parameters:", search.best_params_)

#     if search.best_score_ > best_model_score:
#         best_modal = search
#         best_modal_name = name
#         best_model_score = search.best_score_

#     print('-' * 100)

# print('Best Model Name:', best_modal_name)
# print('Best Model Score:', best_model_score)

In [33]:
svr_params = {
        "kernel":['linear', 'poly'],
        "degree":[1 , 3 , 25],
}

In [34]:
# search = RandomizedSearchCV(
#         estimator=SVR(),
#         cv=5,
#         param_distributions=svr_params,
#         n_iter=2,
#         random_state=42,
#         scoring="r2"
#     )

# search.fit(X_train_scal, y_train)
# y_predict = search.predict(X_test_scal)

# print("Best Score:", search.best_score_)
# print("R2 Score:", r2_score(y_test, y_predict))
# print("Best Parameters:", search.best_params_)

In [35]:
X_train_scal.shape

(80000, 8)

In [36]:

# Use a subset for hyperparameter tuning
n_search = 15000

rng = np.random.RandomState(42)
idx = rng.choice(len(X_train_scal), n_search, replace=False)

X_search = X_train_scal[idx]
y_search = y_train.iloc[idx] if hasattr(y_train, "iloc") else y_train[idx]

In [37]:
search = RandomizedSearchCV(
        estimator=SVR(),
        cv=5,
        param_distributions=svr_params,
        n_iter=2,
        random_state=42,
        scoring="r2"
    )

In [38]:
search

RandomizedSearchCV(cv=5, estimator=SVR(), n_iter=2,
                   param_distributions={'degree': [1, 3, 25],
                                        'kernel': ['linear', 'poly']},
                   random_state=42, scoring='r2')

In [39]:
search.fit(X_search, y_search)

RandomizedSearchCV(cv=5, estimator=SVR(), n_iter=2,
                   param_distributions={'degree': [1, 3, 25],
                                        'kernel': ['linear', 'poly']},
                   random_state=42, scoring='r2')

In [40]:
print("Best Score:", search.best_score_)
print("Best Parameters:", search.best_params_)

Best Score: 0.8620663992165675
Best Parameters: {'kernel': 'linear', 'degree': 1}

In [41]:
final_svr = SVR(kernel='linear', degree=1)

In [42]:
final_svr.fit(X_train_scal , y_train)

SVR(degree=1, kernel='linear')

In [43]:
y_predict = final_svr.predict(X_test_scal)

In [44]:
y_predict

array([ 590.17283561, 4363.7844528 , 6273.51012609, ..., -911.41785502,
       2989.46259855, -935.70684912], shape=(20000,))

In [45]:
print("R2 Score:", r2_score(y_test, y_predict))

R2 Score: 0.8762840265454583

In [46]:
LR_params = {
    'fit_intercept': [True, False],
    'copy_X': [True, False],
    'n_jobs': [None, 1, 2, 3, 5]
}

In [47]:
search = RandomizedSearchCV(
    estimator=LinearRegression(),
    cv=5,
    param_distributions=LR_params,
    n_iter=2,
    random_state=42,
    scoring="r2"
)

In [48]:
search.fit(X_train, y_train)

RandomizedSearchCV(cv=5, estimator=LinearRegression(), n_iter=2,
                   param_distributions={'copy_X': [True, False],
                                        'fit_intercept': [True, False],
                                        'n_jobs': [None, 1, 2, 3, 5]},
                   random_state=42, scoring='r2')

In [49]:
print("Best Parameters:", search.best_params_)
print("Best R2 Score:", search.best_score_)

Best Parameters: {'n_jobs': None, 'fit_intercept': True, 'copy_X': True}
Best R2 Score: 0.8750625047118514

In [56]:
XGBR_params = {
    'n_estimators': [50, 100, 200],
    'max_depth': [3, 5, 6, 7, 10],
    'learning_rate': [0.01, 0.05, 0.1, 0.2],
    'subsample': [0.8, 1.0],
    'colsample_bytree': [0.8, 1.0]
}

In [57]:
search = RandomizedSearchCV(
    estimator=XGBRegressor(),
    cv=5,
    param_distributions=XGBR_params,
    n_iter=2,
    random_state=42,
    scoring="r2"
)

In [58]:
search.fit(X_train, y_train)

RandomizedSearchCV(cv=5,
                   estimator=XGBRegressor(base_score=None, booster=None,
                                          callbacks=None,
                                          colsample_bylevel=None,
                                          colsample_bynode=None,
                                          colsample_bytree=None, device=None,
                                          early_stopping_rounds=None,
                                          enable_categorical=True,
                                          eval_metric=None, feature_types=None,
                                          feature_weights=None, gamma=None,
                                          grow_policy=None,
                                          importance_type=None,
                                          interaction_constraints...
                                          max_leaves=None,
                                          min_child_weight=None, missing=nan,
                                          monotone_constraints=None,
                                          multi_strategy=None,
                                          n_estimators=None, n_jobs=None,
                                          num_parallel_tree=None, ...),
                   n_iter=2,
                   param_distributions={'colsample_bytree': [0.8, 1.0],
                                        'learning_rate': [0.01, 0.05, 0.1, 0.2],
                                        'max_depth': [3, 5, 6, 7, 10],
                                        'n_estimators': [50, 100, 200],
                                        'subsample': [0.8, 1.0]},
                   random_state=42, scoring='r2')

In [59]:
print("Best Parameters:", search.best_params_)
print("Best R2 Score:", search.best_score_)

Best Parameters: {'subsample': 1.0, 'n_estimators': 200, 'max_depth': 10, 'learning_rate': 0.05, 'colsample_bytree': 1.0}
Best R2 Score: 0.9995002371360806